### ISSUE TITLE
How to specify/pass browser version?

### ISSUE THREAD

**Issue by sijosyn** [alexschwantes/testcafe-browser-provider-selenium#1]
Hi Alex. Is there a way we pass/specify the browser version for e.g selenium:chrome:66 or selenium:edge:16 ? Can you provide us this option? Thanks.

**Comment by alexschwantes** [comment]
Hi Sijo, 
I've just pushed an update to the package (0.2.0) that should allow you to specify the browser name and version. see the readme for how to structure it. 

Can you let me know if this works for you?

**Comment by sijosyn** [comment]
Thanks Alex. :+1: Works fine. You can close this issue.

**Comment by alexschwantes** [comment]
great to hear :)
