### ISSUE TITLE
WebDriverError: java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by shyedhu** [alexschwantes/testcafe-browser-provider-selenium#12]
Hi, 
      I'm not able to connect one of selenium remote grid through testcafe-browser-provider-selenium plugin and getting browser open on remote host , however getting empty white screen (it says keep on loading the browser in remote host) , I'm not sure this is due to proxy issue or other capabilities that i need to disable in capabilities.json during the run .. Can you please let me know what is right capabilities.json file data to resolve the 

Here’s my run command :
 SELENIUM_SERVER=http://{my_remote_grid_host:portNumber}/wd/hub testcafe selenium:chrome tests/exampleTest.js

Here’s error getting during test run : 
ERROR Was unable to open the browser "selenium:chrome" due to error.

WebDriverError: java.net.ConnectException: Connection refused (Connection refused)
    at Object.checkLegacyResponse (/node_modules/selenium-webdriver/lib/error.js:585:15)
    at parseHttpResponse (/node_modules/selenium-webdriver/lib/http.js:556:13)
    at Executor.execute (/node_modules/selenium-webdriver/lib/http.js:491:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)

If i want to try the  SELENIUM_CAPABILITIES="capabilities.json" , it also doesn't work , what is correct JSON data for chrome and firefox browser ,I tried following the default one ,it doesn't work 

{
    "chrome@73": {
        "chromeOptions": {
            "args": [
                "headless",
                "--use-fake-ui-for-media-stream",
                "--use-fake-device-for-media-stream",
                "--allow-http-screen-capture",
                "--disable-web-security"
            ]
        }
    }
}

**Comment by shyedhu** [comment]
Hi @alexschwantes,
Could you please help me on these ?

What is correct selenium capabilities for running chrome browser on remote grid box (if that grid will allow no-sandbox mode and that grid has handled proxy )
I tried all below the options ,however it still not working here ,

 My remote grid's chrome browser version is : chrome@81.0.4044

Here's my capabilities.json
=========================
{
 "chrome@81.0.4044": {
        "chromeOptions": {
            "args": [
                "--no-sandbox",
                "--disable-setuid-sandbox",
                "--no-proxy-server",
                "--disable-popup-blocking",
                "--use-fake-ui-for-media-stream",
                "--use-fake-device-for-media-stream",
                "--allow-http-screen-capture",
                "--disable-web-security",
                "--disable-dev-shm-usage",
                "--force-effective-connection-type"
            ]
        }
    }
}
===================
Here's My testcafe version and testcafe-browser-provider-selenium plugin version are
"testcafe": "^1.7.0",
"testcafe-browser-provider-selenium": "^0.4.0"

Here’s my run command
======================
SELENIUM_SERVER=http://{my_remote_grid_host:portNumber}/wd/hub SELENIUM_CAPABILITIES="capabilities.json"  testcafe selenium:chrome tests/exampleTest.js

========================
Thanks - Shyedhu

**Comment by alexschwantes** [comment]
Hi @shyedhu, 
I'm going to need some more details

- What operating system are you on?
- Where is your remote grid running?
- How are you setting the environment variables?
- can you load http://my_remote_grid_host:portNumber/wd/hub/status

ie. on windows you might run the following commands in a command prompt (remove capabilities.json for now)
```
set SELENIUM_SERVER=http://{my_remote_grid_host:portNumber}/wd/hub
testcafe selenium:chrome tests/exampleTest.js
```

Try a simple test like putting this in your `tests/exampleTest.js`
```
import { Selector } from 'testcafe';

fixture('example.com').page('http://www.example.com')
  test('load example page', async t => {
    await t.expect(Selector('h1').innerText).eql('Example Domain');
    await t.click(Selector('a'));
  });
```

**Comment by shyedhu** [comment]
Hi @alexschwantes, Thanks for your response !

Please find below my inline response 

What operating system are you on?

**[Shyedhu]** - macOS V10.14

Where is your remote grid running?

**[Shyedhu]** My remote Selenium Grid (zalenium) Hub v.3.141.59 running on AWS ECS

How are you setting the environment variables?

So far I didn’t set any environment variable on Mac machine , I just used following the variable on my run command  in my macOS on every time

Here’s my run command :

SELENIUM_SERVER=http://{my_remote_grid_hub_host:portNumber}/wd/hub SELENIUM_CAPABILITIES="capabilities.json" testcafe selenium:chrome tests/exampleTest.js

can you load http://my_remote_grid_host:portNumber/wd/hub/status

**[Shyedhu]** I was able to load it and got status:0 and os : { name - “Linux”, version: "4.14……x86_64" } 

Try a simple test like putting this in your tests/exampleTest.js

**[Shyedhu]** I tried following simple test  in my tests/exampleTest.js , however it doesn’t work and was getting WebDriverError: java.net.ConnectException: Connection refused (Connection refused) in console terminal and was getting empty white screen on remote selenium grid hub host (please find attached the screenshot) for reference

import { Selector } from 'testcafe';

fixture('example.com').page('http://www.example.com')
  test('load example page', async t => {
    await t.expect(Selector('h1').innerText).eql('Example Domain');
    await t.click(Selector('a'));
  });

Kindly note : In fact I was able to connect the chrome browser on My remote Selenium Grid (zalenium) Hub v.3.141.59, However page not connected and was getting empty white screen on remote selenium hub grid host (please find attached the screenshot) for reference.. I think i need to modify "capabilities.json" , but i was not sure what exact values needs to be added for this case , can you help to modify "capabilities.json" for this case , Please ?
<img width="245" alt="web page not loading on selenium grid hub" src="https://user-images.githubusercontent.com/8210719/82847397-c548e200-9ea2-11ea-9055-282df2ba8a06.png">

**Comment by alexschwantes** [comment]
In order to set an environment variable for your terminal sesson on mac, you need to use the `export` command. Try running the following commands in a terminal window. Forget about capabilities.json for now, in fact delete the file completely so that it doesn't interfere in debugging the issue. Once you get it working without it you can then try using it.

```
export SELENIUM_SERVER=http://{my_remote_grid_hub_host:portNumber}/wd/hub
testcafe selenium:chrome tests/exampleTest.js
```

If this doesn't work then perhaps try running vanilla selenium grid, I haven't tested it with Zalenium.

**Comment by shyedhu** [comment]
Hi @alexschwantes  

I completely deleted the capabilities.json from my workspace and then re-tried your command through Zalenium and got below the error  and also noticed that white screen on Zalenium , please find attached the screenshot for your reference 

<img width="245" alt="web page not loading on selenium grid hub" src="https://user-images.githubusercontent.com/8210719/83184375-39bb9500-a0de-11ea-9f3d-372895a37b35.png">

```
ERROR Was unable to open the browser "selenium:chrome" due to error.
WebDriverError: java.net.ConnectException: Connection refused (Connection refused)
    at Object.checkLegacyResponse (/node_modules/selenium-webdriver/lib/error.js:585:15)
    at parseHttpResponse (/node_modules/selenium-webdriver/lib/http.js:556:13)
    at Executor.execute (/node_modules/selenium-webdriver/lib/http.js:491:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

And also I tried the same command on vanilla selenium grid ,and got below the error , Can you please take a look ?

ERROR Was unable to open the browser "selenium:chrome" due to error.

Error: ECONNRESET socket hang up
    at ClientRequest.<anonymous> (/node_modules/selenium-webdriver/http/index.js:262:15)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at Socket.socketOnEnd (_http_client.js:426:9)
    at Socket.emit (events.js:203:15)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by alexschwantes** [comment]
So I tried running selenium grid locally and everything worked (on localhost without docker). But when I tried to run it via the selenium (debug) docker images where you can connect with vnc to see the browser, it failed with the blank page as you showed. With firefox, it eventually timed out and showed that it was having trouble connecting back to the ip address of the host machine where I was running testcafe from. 
I upgraded docker on the host machine and tried again, and everything works. 

I believe what is happening is that testcafe communicates to selenium hub to start the browser, which then tries to connect back to Testcafe to proxy the web page to load. This is how Testcafe works. Initially there was an issue with the network configuration that didn't allow that but recent docker builds have changed how networking works and the selenium node was able to communicate back to the host machine where I was running Testcafe. 

If you are running this in the cloud, try spinning up a virtual machine in the same network (or remote into the selenium hub machine) and run testcafe from there. Or you could put in place some network configuration to allow the selenium nodes to communicate back to your host machine where you are running testcafe.

**Comment by alexschwantes** [comment]
Closing as I haven't heard back from user. Please comment if this is still an issue.
