### ISSUE TITLE
Can i pass user agent to use android chrome with this package

### ISSUE THREAD

**Issue by saurabh2k26** [alexschwantes/testcafe-browser-provider-selenium#15]
With local chrome browser, we have capability to use user agent like this:
`testcafe "chrome --user-agent='Mozilla/5.0\ \(Linux\;\ Android\ 5.0\;\ SM-G900P\ Build/LRX21T\)\ AppleWebKit/537.36\ \(KHTML,\ like\ Gecko\)\ Chrome/57.0.2987.133\ Mobile\ Safari/537.36'" test.js`

This gives me, logs like 
```
Running tests in:
 - Chrome 57.0.2987.133 / Android 5.0
```

Can i replicate this with your package:
I tried:
`testcafe selenium:"chrome --user-agent='Mozilla/5.0\ \(Linux\;\ Android\ 5.0\;\ SM-G900P\ Build/LRX21T\)\ AppleWebKit/537.36\ \(KHTML,\ like\ Gecko\)\ Chrome/57.0.2987.133\ Mobile\ Safari/537.36'" test.js`

But , it's not working.
PS: i have selenium hub and chrome node up and running.

**Comment by alexschwantes** [comment]
checkout version 1.0,0 and the readme on how to use this :)
