### ISSUE TITLE
Selenium Grid v4-alpha-6 with https not working with this plugin

### ISSUE THREAD

**Issue by ambirag** [alexschwantes/testcafe-browser-provider-selenium#19]
I am running selenium grid [v4-alpha-6 running on K8s with traefik](https://medium.com/@eelam.ragavan/selenium-grid-version-4-alpha-6-using-kubernetes-bfee32231c68). Here my hub url will be like https://test.hub.xyz.org.com/wd/hub with HTTPS protocol.

This is how I am running the test:
`
export NODE_TLS_REJECT_UNAUTHORIZED=0
npm config set strict-ssl false

export SELENIUM_SERVER="https://test.hub.xyz.org.com/wd/hub"
testcafe "selenium:chrome" scripts/scripts.js 
`
This is the exception I get  every time I run a test against TestCafe using this plugin.

```
18:21:49 updated 1 package in 2.402s
18:22:58 ERROR Was unable to open the browser "selenium:chrome" due to error.
18:22:58 
18:22:58 ScriptTimeoutError: NettyHttpHandler request execution error
18:22:58     at Object.throwDecodedError (/data/jenkins/.nvm/versions/node/v9.4.0/lib/node_modules/testcafe-browser-provider-selenium/node_modules/selenium-webdriver/lib/error.js:550:15)
18:22:58     at parseHttpResponse (/data/jenkins/.nvm/versions/node/v9.4.0/lib/node_modules/testcafe-browser-provider-selenium/node_modules/selenium-webdriver/lib/http.js:565:13)
18:22:58     at Executor.execute (/data/jenkins/.nvm/versions/node/v9.4.0/lib/node_modules/testcafe-browser-provider-selenium/node_modules/selenium-webdriver/lib/http.js:491:26)
18:22:58     at <anonymous>
18:22:58     at process._tickCallback (internal/process/next_tick.js:160:7)
18:22:58 
18:22:58 Type "testcafe -h" for help.
```

Full printed log
https://gist.github.com/ambirag/7a3558cfd646fb2eb217d7eb4080d047 

Here the IP and  in other exceptions is the IP of the Node Pod where browser Chrome was running.
```
cdp: 'http://10.2.xx.xxxx:5555/session/0437b82665405bade94f2fe0931d0d3f/se/cdp
```

Hub is running fine:ttps://test.hub.xyz.org.com/wd/hub/status

I can see the session details under /wd/hub/status once test start to run but test fails with error shown above.

```
{
  "value": {
    "ready": true,
    "message": "Selenium Grid ready.",
    "nodes": [
      {
        "id": "b8f08baa-0e04-4326-a9d3-xxxx",
        "uri": "http:\u002f\u002f10.x.x.x:5555",
        "maxSessions": 1,
        "stereotypes": [
          {
            "capabilities": {
              "browserName": "chrome"
            },
            "count": 1
          }
        ],
        "sessions": [
        ]
      }
    ]
  }
}


```

I tried with capabilities.json like this as well

```
{
    "chrome": {
        "goog:chromeOptions": {
            "w3c": true/false,
            "args": [
                "--ignore-certificate-errors",
                "--no-sandbox",
                "--no-proxy-server",
                "--test-type",
                "--disable-web-security",
                "--allow-insecure-localhost",
                "--disable-gpu"
            ]
        }
    }
}
```
This plugin does work if I run Selenium v4 grid locally like this with HTTP
```
docker network create grid
$ docker run -d -p 4444:4444 --net grid --name selenium-hub selenium/hub:4.0.0-alpha-6-20200730
$ docker run -d --net grid -e HUB_HOST=selenium-hub -v /dev/shm:/dev/shm selenium/node-chrome:4.0.0-alpha-6-20200730
$ docker run -d --net grid -e HUB_HOST=selenium-hub -v /dev/shm:/dev/shm selenium/node-firefox:4.0.0-alpha-6-20200730
export SELENIUM_SERVER=http://localhost:4444/wd/hub
testcafe -c 4 "selenium:chrome" scripts/scripts.js
```

But my hub runs on k8s with treafik, and we use https, can you help why this is not working?

**Comment by alexschwantes** [comment]
Hi, 
Unfortunately there is a little bit of a mix in versions between selenium (hub) and welenium-webdriver. 
https://www.selenium.dev/blog/2020/selenium-4-alpha-6-is-out/ was released on June 1, 2020, however the latest version of selenium-webdriver (which we are using, [4.0.0-alpha.7](https://www.npmjs.com/package/selenium-webdriver/v/4.0.0-alpha.7)) was published 5 months ago. 

The stack trace that is thrown looks like it is coming from selenium-webdriver as it is trying to parse the http response from the server. 

Can you try to create a basic project in javascript with selenium-webdriver (without using testcafe) and then run it on your cluster? That will remove testcafe and this provider plugin from the equation to tell you if the js webdriver is compatible with your cluster configuration..

**Comment by ambirag** [comment]
@alexschwantes 
I tried running a sample ScalaTest project, which uses v3.141.59 library and it was able to run a test successfully against this grid running v4-alpha-6.

**Comment by ambirag** [comment]
I can check this again with javascript + selenium-webdriver 4-alpha-6 version.
btw, this is the console log when the failure happens - https://gist.github.com/ambirag/7a3558cfd646fb2eb217d7eb4080d047 the IP mentioned here is the IP of the Chrome Node Pod.

**Comment by ambirag** [comment]
@alexschwantes I tried with a simple javascript using  selenium-webdriver@4.0.0-alpha.7 npm library and pointed it to my https based selenium v4-alpha-6 grid and it worked. So I guess the issue is with TestCafe + how this plugin works with the grid.
One interesting error when running with testcafe against my grid is this error
```
Caused by: java.util.concurrent.TimeoutException: Request timeout to 10.2.xx.xxx/10.2.71.224:5555 after 60000 ms\n' 
```

This IP is the ip address of the Chrome Node Pod in k8s cluster. I am not sure if testcafe is trying to reach the node directly?

**Comment by alexschwantes** [comment]
@ambirag yes testcafe runs by proxying all pages via the testcafe server through to the browsers, so it needs direct access to the browsers. https://devexpress.github.io/testcafe/documentation/how-it-works/

Where are you running the tests from? Is it locally or from within the cluster? 
Are you able to run the tests such that testcafe has access to the Chrome Node Pod?

**Comment by ambirag** [comment]
@alexschwantes  It works with regular Selenium Grid running in AWS with node's private IP accessible to TestCafe but when the grid is running in k8s, the Node Pod's  IP will not be accessible outside, unless TestCafe itself running inside the cluster(I haven't tried this yet)

**Comment by alexschwantes** [comment]
@ambirag did you try running testcafe inside the cluster, where it can access the Pods? I think this would be the easiest way to run this. Alternatively configuring a service to allow communication to the pods might work, but would be more work https://kubernetes.io/docs/tutorials/services/source-ip/

**Comment by alexschwantes** [comment]
Closing as I haven't heard back from user. Please comment if this is still an issue.

**Comment by aragavan1** [comment]
Selenium grid now provides a env variable called SE_NODE_GRID_URL which can be passed to grid nodes so CDP internal ip url can be replaced with hub url. - see https://github.com/seleniumHQ/selenium/issues/9202 for reference.
But even with this, when I run testcafe against selenium grid v4, I see the browser is trying a url like this in the attached image 
<img width="1370" alt="Screenshot 2021-09-10 at 11 48 29" src="https://user-images.githubusercontent.com/77582557/132842456-e01ca8b1-b02b-4833-b83b-3a6e6a01547e.png">

Because this env variable is set, I can see this in the node config so I expect testcafe cdp url will be using this but it still uses a private IP as shown in the screenshot. btw, it is **HTTPS**

[node]
grid-url = "https://test322.us-west-2.dev.test.com"
session-timeout = "180"
override-max-sessions = false
detect-drivers = false
max-sessions = 1

and grid cdp url also looks like this "se:cdp": "wss://test322.us-west-2.dev.test.com/session/44d984661045fd76d8b0da6570fd0886/se/cdp",

Any help is will be appreciated @alexschwantes
