### ISSUE TITLE
Unable to pass browser CLI argument as environment variable (parsing error)

### ISSUE THREAD

**Issue by mfestrada** [alexschwantes/testcafe-browser-provider-selenium#23]
Whenever I attempt to specify the browser CLI argument as an environment variable, the string is parsed incorrectly.

Using the following command to invoke tests unexpectedly fails:
```shell
export SELENIUM_SERVER=http://foo.bar:4444/wd/hub
export SELENIUM_BROWSER=selenium:chrome
npx testcafe ${SELENIUM_BROWSER}
```

The error thrown indicates the string is parsed incorrectly, with items shifted so that the `selenium` substring is passed for the `browserName` field and the browser name is passed for `browserVersion`:

```
The "browsers", "filter" options from the configuration file will be ignored.
ERROR Was unable to open the browser "selenium:chrome" due to error.

WebDriverError: Error forwarding the new session cannot find : Capabilities {browserName: selenium, browserVersion: chrome}
    at Object.checkLegacyResponse (/Users/Mike/Development/foo/node_modules/selenium-webdriver/lib/error.js:585:15)
    at parseHttpResponse (/Users/Mike/Development/foo/node_modules/selenium-webdriver/lib/http.js:556:13)
    at Executor.execute (/Users/Mike/Development/foo/node_modules/selenium-webdriver/lib/http.js:491:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Type "testcafe -h" for help.
```

If I forgo using an environment variable to define the browser then this works as expected.

**Comment by alexschwantes** [comment]
Hi 
`SELENIUM_BROWSER` environment variable is used by Selenium to set its browser configuration, so by setting that to the testcafe browser name you are overwriting the selenium configuration set by testcafe which is why its not working. If you want to pass 'selenium:chrome' via environment variable, try a different environment variable, like `TESTCAFE_BROWSER`, then it will work. :)

**Comment by mfestrada** [comment]
Thank you @alexschwantes!! I didn't realize I was clobbering that variable, I'll try another name out and keep you posted.

**Comment by alexschwantes** [comment]
no problem. I'll close the ticket, if you have any issues please re-open. :)
