### ISSUE TITLE
Multi Window Error while running test cases

### ISSUE THREAD

**Issue by bharat-maher** [alexschwantes/testcafe-browser-provider-selenium#26]
Getting this error while running a test using 'selenium: chrome'

`Multi window mode is supported in Chrome, Chromium, Edge 84+ and Firefox only. Run tests in these browsers to use the "openWindow" method`

I tried with the latest version of **Testcafe** and **testcafe-browser-provider-selenium**

**Comment by alexschwantes** [comment]
Hi I'm going to need more information:
1. are you using any 'openWindow' methods in your test? This feature is in [Beta](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/multiple-browser-windows.html) at testcafe and only supported on local browsers
1. can you try a simple test where you just open up a web page and see if that works, without any extra logic.
1. can you try with testcafe-browser-provider-selenium version 1.0.1 and see if you are getting the same result

Also any information on how your are running your tests and your selenium config would be helpful if the above doesn't provide any insights

**Comment by bharat-maher** [comment]
Hello @alexschwantes : 
 
Here I give you all the details. 
        
     1. Yes. I am using 'openWindow' methods in my test. Is it still in Beta mode with version [TestCafe v1.11.0 Released](https://devexpress.github.io/testcafe/blog/testcafe-v1-11-0-released.html)
     2.

**Comment by bharat-maher** [comment]
Hello @alexschwantes : 
 
Here I give you all the details. 
        
     1. Yes. I am using 'openWindow' methods in my test. Is it still in Beta mode with version [TestCafe v1.11.0 Released](https://devexpress.github.io/testcafe/blog/testcafe-v1-11-0-released.html)
     2. Yes. I need to open a new window to perform some testing.
     3. Simple test is working. In fact, 'openWindow' also works with Chrome in local machine but not in selenium grid.
     4. Yes I tried and testcafe-browser-provider-selenium version 1.0.1 giving me the same error.

I am running testcafe test automation testing using a selenium grid and to connect selenium grid I am using testcafe-browser-provider-selenium library. 

Everything is working fine Just multi window is not test is not working.

**Comment by alexschwantes** [comment]
The Beta versions of multi window functionality of Testcafe was [only supported on local instances](https://devexpress.github.io/testcafe/media/team-blog/introducing-multi-window-tests-beta.html) of Chrome and Firefox.
I can see that the latest v1.11.0 testcafe release on the 15th Feb 2021 (2 days ago) now says it is stable, however no mention of local vs remote support.. 

It seems that it is not yet supported for custom browser providers like this:
* https://github.com/DevExpress/testcafe/issues/5963
* https://github.com/DevExpress/testcafe/issues/5651 "Once it is released, we will consider supporting multiple windows for custom browser providers."

So unfortunately there is no support for this feature for browser providers as yet.

**Comment by bharat-maher** [comment]
Yes. At this moment it only supports Chrome and Firefox. @alexschwantes thanks for your help. I will keep eye on the Testcafe release version. I Hope will get this feature soon.

**Comment by aviv-saranrajprabhakaran** [comment]
Hi @alexschwantes, I'm facing the below Error when I tried to execute my testcafe tests on browserstack browsers (chrome, firefox & safari)

```
Multi-window mode is supported in Chrome, Chromium, Edge 84+ and Firefox only. Run tests in these browsers to use the "closeWindow" method.
                
Browser: Chrome 89.0.4389.90 / Windows 10
```

I'm using the latest version of testcafe 1.14.0 & testcafe-browser-provider-browserstack 1.13.1

Note: 
1. Test execution is successful when I tried with local instances of chrome, firefox & safari
2. I'm using t.closeWindow() to close the current active window

**Comment by alexschwantes** [comment]
Hi @Saranraj2022, please read the comments on this issue. It has been closed as it is not supported by Testcafe. Testcafe only supports this feature when run locally, not remotely. You can see some issues from DevExpress in the comments above where you can comment on and ask them to implement this functionality.
