### ISSUE TITLE
Run the testcafe on hosted selenium grid

### ISSUE THREAD

**Issue by dudaming** [alexschwantes/testcafe-browser-provider-selenium#3]
Hi Alex,

Thanks for the package. When I run selenium grid, it works.
However, we have selenium grid host on AWS, when I try to run the test with the hosted selenium, I can see that the tests are running. I cannot see the logs of the running test.

Do you have any good practice for this?

Thanks,
Daming

**Comment by alexschwantes** [comment]
Hi @dudaming, sorry for the late reply. 
How is your setup configured? Is testcafe run from within AWS as well?
Are the logs produced at the end of the test and you just want to see them during the running?
Do you run it with any reporters configured like the xUnit one?
