### ISSUE TITLE
Testcafe plugin not working with Selenium Grid implementation in K8s 

### ISSUE THREAD

**Issue by aragavan1** [alexschwantes/testcafe-browser-provider-selenium#35]
All the details are here in https://github.com/alexschwantes/testcafe-browser-provider-selenium/issues/19 but because it is closed, opening a new one with more details and rc2 of Selenium Grid v4

Selenium grid now provides a env variable called SE_NODE_GRID_URL which can be passed to grid nodes so CDP internal ip url can be replaced with hub url. - see https://github.com/SeleniumHQ/selenium/issues/9202 for reference.
But even with this, when I run testcafe (plugin) against selenium grid v4, I see the browser is trying a url like this in the attached image

![image](https://user-images.githubusercontent.com/77582557/134021708-32eec96d-b2f0-4f0f-8ea5-e8b080c1c17a.png)

Because this env variable is set, I can see this in the node config so I expect testcafe cdp url will be using this but it still uses a private IP as shown in the screenshot. btw, it is HTTPS as well.

[node]
grid-url = "https://test322.us-west-2.dev.test.com"
session-timeout = "180"
override-max-sessions = false
detect-drivers = false
max-sessions = 1

and grid cdp url also looks like this "se:cdp": "wss://test322.us-west-2.dev.test.com/session/44d984661045fd76d8b0da6570fd0886/se/cdp",

**Comment by aragavan1** [comment]
@alexschwantes  any help would be really appreciated :)

**Comment by alexschwantes** [comment]
hi @aragavan1,
Please read the comments on #19. All nodes need direct access to testcafe, this is how testcafe works. Testcafe doesn't know anything about the selenium docker image variable SE_NODE_GRID_URL, which appears to be related to specifically CDP and live preview while running sessions. Testcafe also doesn't know anything about CDP. 

So I'm sorry, but unfortunately what you are trying to do just isn't possible.
