### ISSUE TITLE
Incorrect tests behaviour when run concurrently on chrome grid

### ISSUE THREAD

**Issue by wombatka** [alexschwantes/testcafe-browser-provider-selenium#40]
We are having an issue when running tests with concurrency (occurs even with -c 2) on chrome selenium grid ( not occurs on firefox). Tests reporter does not output any results and the tests get stuck until you manually open and focus the browser- then the browsers are eventually closed and build finishes. All the details and reproduction steps are present here: https://github.com/DevExpress/testcafe/issues/7164 as i have initially thought that this is testcafe issue, hence created it for testcafe.

**Comment by alexschwantes** [comment]
Hi @wombatka, it appears that your setup of selenium grid is done incorrectly. In your steps to reproduce you execute:

```1.run grid with: sudo docker run -d -p 4444:4444 -p 7900:7900 --name=chromeGrid --shm-size="2g" -e 'VNC_NO_PASSWORD=1' -e 'SCREEN_WIDTH=1680' -e 'SCREEN_HEIGHT=1050' -e 'SE_NODE_MAX_SESSIONS=7' selenium/standalone-chrome```

This does not do what you think it does. It starts a standalone server with **1 chrome browser and a concurrency of 1.**

If you go to http://localhost:4444/ you will see that selenium is configured with only a concurrency of 1. Hence running testcafe with a concurrency of 5 against that server will lead to failure.


Instead, if you set it up as per the instructions from https://github.com/alexschwantes/testcafe-browser-provider-selenium it will work as expected. 

IE. for a concurrency of 5 chrome browsers
ie. 
```
docker network create grid
docker run -d -p 4442-4444:4442-4444 --net grid --name selenium-hub selenium/hub
docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub --shm-size="2g" -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 selenium/node-chrome
docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub --shm-size="2g" -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 selenium/node-chrome
docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub --shm-size="2g" -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 selenium/node-chrome
docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub --shm-size="2g" -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 selenium/node-chrome
docker run -d --net grid -e SE_EVENT_BUS_HOST=selenium-hub --shm-size="2g" -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 selenium/node-chrome
```
http://localhost:4444/ will show
![image](https://user-images.githubusercontent.com/2829978/189335905-910b2149-6c15-47d0-bdc1-ab0dd9e21141.png)

and `npm test` will run 5 tests in parallel and produce the output:
```
> testcafeexample@1.0.0 test
> testcafe -c 4 selenium:chrome example.js

 Running tests in:
 - Chrome 105.0.0.0 / Linux 0.0
 - Chrome 105.0.0.0 / Linux 0.0
 - Chrome 105.0.0.0 / Linux 0.0
 - Chrome 105.0.0.0 / Linux 0.0
 Startup time (11s)

 example
I value is: 0
I value is: 1
 √ E1  (14s)
I value is: 2
I value is: 3
 √ E2  (14s)
 √ E3  (14s)
 √ E4  (14s)
I value is: 4
I value is: 5
I value is: 6
 √ E5  (12s)
 √ E6  (12s)
I value is: 7
 √ E7  (12s)
 √ E8  (12s)
I value is: 8
 √ E9  (7.53s)
I value is: 9
I value is: 10
I value is: 11
 √ E10  (7.73s)
 √ E11  (7.56s)
 √ E12  (7.35s)
I value is: 12
 √ E13  (7.31s)
I value is: 13
I value is: 14
 √ E14  (8.14s)
 √ E15  (8.03s)
 √ E16  (8.52s)
I value is: 15
 √ E17  (9.13s)
I value is: 16
I value is: 17
 √ E18  (8.31s)
 √ E19  (7.69s)
I value is: 18
 √ E20  (7.17s)
I value is: 19
I value is: 20
 √ E21  (8.27s)
I value is: 21
I value is: 22
 √ E22  (8.35s)
 √ E23  (8.29s)
 √ E24  (8.15s)
I value is: 23
 √ E25  (7.97s)
I value is: 24
 √ E26  (8.26s)

 example Duration (1m 06s)

 26 passed (1m 06s)       
 Total time (1m 18s)      

```

**Comment by wombatka** [comment]
HI .Identical setup works for firefox without any problem. There is one node with 5 sessions and tests are run in each of the sessions. Everything works as expected on firefox with my setup. Only on chrome there is a problem. So it is not a matter of my grid setup but setup+ chrome. Unfortunately I cannot start grid with five separate nodes as mentioned in your suggestion . It is much more memory consuming and our jenkins cannot handle that .

**Comment by alexschwantes** [comment]
As to why it works with firefox and not chrome standalone, you will have to ask Selenium. 

When you run the command you posted on the ticket for standalone chrome and then load the selenium grid webpage it will show selenium Grid is running with 1 worker/node with a **Max Concurrency: 1**. In that configuration, Selenium Grid is the limiting factor for why it isn't running concurrently. You can try playing around with some of the variables you pass through to selenium ie. https://github.com/SeleniumHQ/docker-selenium#increasing-session-concurrency-per-container states you should also override `SE_NODE_OVERRIDE_MAX_SESSIONS` to `true`. 

Anyway, it won't work until Selenium Grid increases its maximum concurrency as viewed in the grid webpage. If you need help in achieving this, ask on [docker-selenium](https://github.com/SeleniumHQ/docker-selenium)
