### ISSUE TITLE
New version coming??

### ISSUE THREAD

**Issue by jhernandez-iriusrisk** [alexschwantes/testcafe-browser-provider-selenium#46]
Hi, it is been +2 years since last release, is it coming any new version or features? thank you in advance

**Comment by alexschwantes** [comment]
Generally the browser providers just work. Was there something in particular that you were missing?

**Comment by jhernandez-iriusrisk** [comment]
The plugin works fine, it is just to know if there is a coming version with new features or similar. 
Conversely, parallel sessions don't work "as expected". Testcafe opens several tabs and it sends one command to the first tab, when it finishes, it sends another command to the second tab, etc. So it does not work like Selenium parallel sessions which are able to work with several Selenium browser containers and send commands in parallel. 
Do you know if this is how testcafe works or plugin behavior?
Thank you in advance.

**Comment by alexschwantes** [comment]
At present there is nothing new planned.
Have a read of #40 and see if that can help you debug why parallel execution isn't working. You could also test it in different browsers to see if it is the same issue across browsers.
