### ISSUE TITLE
Tests against a remote Selenium Grid time out because Testcafé seems to try making the Grid browser reach the host it runs on

### ISSUE THREAD

**Issue by manuelkiessling** [alexschwantes/testcafe-browser-provider-selenium#5]
Hi,

I've created a gist with the very simple "litmus" test setup I'm using to verify the problem at https://gist.github.com/manuelkiessling/81a61c42df3edfa3bd2af60bdbed81fd.

I'm only using Testcafé 1.0.1 and testcafe-browser-provider-selenium 0.3.0, and run my test case against a Selenium Grid.

This works well if the Selenium Grid runs on the same host where I launch the test run.

It fails as soon as the Selenium Grid runs on another, remote host, with the following error:

```
WebDriverError: Reached error page: about:neterror?e=netTimeout&u=http%3A//10.104.8.148%3A58160/browser/connect/0CERNlP&c=UTF-8&f=regular&d=The%20server%20at%2010.104.8.148%20is%20taking%20too%20long%20to%20respond.
    at Object.throwDecodedError (/Users/manuelkiessling/git/selenium-grid/simple-tests/testcafe/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/Users/manuelkiessling/git/selenium-grid/simple-tests/testcafe/node_modules/selenium-webdriver/lib/http.js:542:13)
    at Executor.execute (/Users/manuelkiessling/git/selenium-grid/simple-tests/testcafe/node_modules/selenium-webdriver/lib/http.js:468:26)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

My impression is that Testcafé wants to make the remote browser running in the Grid connect to http://10.104.8.148:58160/browser/connect/0CERNlP, which it can't reach, because `10.104.8.148` is the local IP of the desktop system I'm using to launch the Testcafé run, and which cannot be reached from the Selenium Grid host.

The phenomenon does not occur when running a Selenium test case written in Python (see https://gist.github.com/manuelkiessling/81a61c42df3edfa3bd2af60bdbed81fd#file-simpletest-py) - it works reliably with a local Selenium Grid and with a remote Selenium Grid.

**Comment by manuelkiessling** [comment]
As another litmus test, I've written another simple testcase using `selenium-webdriver` directly, at version `^4.0.0-alpha.1` just as you do:

```
const webdriver = require("selenium-webdriver");

const seleniumAddress = process.env.SELENIUM_SERVER;

const caps = {
  browserName : "firefox",
};

async function basicExample(){
  try {
    const driver = new webdriver.Builder()
      .usingServer(seleniumAddress)
      .withCapabilities(caps)
      .build();


    await driver.get("https://www.galeria-kaufhof.de");

    await driver.getTitle().then(function(title) {
      console.log("The title is: " + title)
    });

    driver.quit();
  }

  catch(err){
    handleFailure(err, driver)
  }

}

basicExample();

function handleFailure(err, driver) {
  console.error("Something went wrong!\n", err.stack, "\n");
  driver.quit();
}
```

This, too, works without issues when running against a remote Selenium Grid host.

**Comment by manuelkiessling** [comment]
I've found https://devexpress.github.io/testcafe/documentation/recipes/test-on-remote-computers-and-mobile-devices.html and realized that making the browser "call back" to the Testcafé system kind of is the point of its "remote" mode. Still not sure how to run tests using a remote system though, unless tests are started from a host that is reachable from the Selenium Grid.

**Comment by manuelkiessling** [comment]
So, looks like my whole approach was fruitless from the beginning and none of the tools involved have any actual issue it's just the way they work. I'll nevertheless keep this here for archeological reasons, it might help other who run into the same trap.

**Comment by dskochubey** [comment]
Hi @manuelkiessling 
How did you set the SELENIUM_SERVER variable to run Testcafé 1.0.1 and testcafe-browser-provider-selenium 0.3.0 against a remote Selenium Grid?

**Comment by alexschwantes** [comment]
@manuelkiessling your gist is on the right track, have a look at the configuration section in the readme, you need to set the SELENIUM_SERVER environment variable to be the remote url to the selenium server.
