### ISSUE TITLE
testcafe server must be accessible from selenium-node?

### ISSUE THREAD

**Issue by gaurav517** [alexschwantes/testcafe-browser-provider-selenium#9]
I am trying to run testcafe tests on selenium grid and in our CI setup, selenium-node is not able to access testcafe server (running on a CI agent), due to network limitations. Selenium-node can only access selenium-hub. Is there a way to get it working in this setup?

Thanks.

**Comment by alexschwantes** [comment]
Why do you want the nodes to access the testcafe server? Is there a specific thing that is failing, like running tests? Testcafe communicates to the selenium hub which in turn communicates to the selenium nodes.
